#import '@/graphql/fragments/SignFragment.gql'

query signs {
    signs {
        ...SignFragment
        signs {
            ...SignFragment
            signs {
                ...SignFragment
            }
        }
    }
}
