#import '@/graphql/fragments/TroopFragment.gql'

query troops {
    troops {
        ...TroopFragment
        troops {
            ...TroopFragment
            troops {
                ...TroopFragment
            }
        }
    }
}
